/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#232a38",
        surface: "#0d1321",
        "on-background": "#dce2f5",
        "surface-container-low": "#151c29",
        "on-primary": "#003543",
        "on-surface": "#dce2f5",
        "on-primary-container": "#00566a",
        "primary-fixed-dim": "#47d6ff",
        "primary-fixed": "#b6ebff",
        outline: "#859399",
        "on-error": "#690005",
        "surface-container-highest": "#2e3543",
        "outline-variant": "#3c494e",
        secondary: "#4edea3",
        background: "#0d1321",
        "secondary-container": "#00a572",
        "surface-container": "#19202d",
        "on-secondary": "#003824",
        "on-primary-fixed": "#001f28",
        "primary-container": "#00d2ff",
        tertiary: "#d6dcfc",
        "on-secondary-container": "#00311f",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "inverse-primary": "#00677f",
        primary: "#a5e7ff",
        "surface-container-lowest": "#070e1b",
        "on-surface-variant": "#bbc9cf",
        "on-secondary-fixed-variant": "#005236",
        "on-secondary-fixed": "#002113",
        "secondary-fixed-dim": "#4edea3",
        "on-tertiary-container": "#474e68",
        "on-tertiary-fixed": "#141a32",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      keyframes: {
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        slideInLeft: {
          "0%": { opacity: "0", transform: "translateX(-40px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
      },
      animation: {
        fadeInUp: "fadeInUp 0.6s ease-out forwards",
        fadeIn: "fadeIn 0.4s ease-out forwards",
        slideInLeft: "slideInLeft 0.6s ease-out forwards",
        float: "float 3s ease-in-out infinite",
      },
      boxShadow: {
        glow: "0 0 20px rgba(0, 210, 255, 0.3)",
        "glow-sm": "0 0 10px rgba(0, 210, 255, 0.2)",
        "glow-lg": "0 0 40px rgba(0, 210, 255, 0.4)",
        card: "0 4px 24px rgba(0, 0, 0, 0.4)",
      },
    },
  },
  plugins: [],
};
